export const cuisineList = [
    "Veg-Burger", 
    "Non-Veg Burger", 
    "Veg Pizza", 
    "NonVeg Pizza", 
    "PanCake", 
    "Donuts", 
    "CupCakes", 
    "veg Noodles", 
    'Egg Noodles', 
    "Non veg Noodles", 
    "Veg Biryani",
    "Non Veg Biryani", 
    "Veg Mandi", 
    "Non veg Mandi", 
    "Veg Starters", 
    "Non veg Starters", 
    "BBQ", 
    "DoraCakes",
    "Cookies",
    "American",
    "BBQ",
    "Breakfast",
    "Burgers",
    "Cafe",
    "Chinese",
    "Desserts",
    "French",
    "Greek",
    "Healthy",
    "Indian",
    "Italian",
    "Japanese",
    "Mexican",
    "Noodles",
    "Organic",
    "Pasta",
    "Pizza",
    "Salads",
    "Seafood",
    "Spanish",
    "Steak",
    "Sushi",
    "Tacos",
    "Tapas",
    "Vegan",
];